require:
  - standard/cop/semantic_blocks
  - ./lib/ruby-next/rubocop.rb

inherit_gem:
  standard: config/base.yml

AllCops:
  Exclude:
    - 'bin/*'
    - '**/tmp/**/*'
    - 'Gemfile'
    - 'vendor/**/*'
    - 'gemfiles/**/*'
    - 'spec/core/**/*'
    - 'spec/language/**/*'
    - 'spec/optional/language/**/*'
    - 'mspec/**/*'
    - 'benchmarks/**/*'
  DisplayCopNames: true
  TargetRubyVersion: next

Standard/SemanticBlocks:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: no_comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: no_comma

Style/Alias:
  Enabled: false

# See https://github.com/rubocop-hq/rubocop/issues/4222
Lint/AmbiguousBlockAssociation:
  Exclude:
    - 'spec/**/*'
    - '**/*.md'

Naming/FileName:
  Enabled: false

Lint/BooleanSymbol:
  Exclude:
    - 'lib/ruby-next/language/rewriters/**/*.rb'

Layout/HeredocIndentation:
  Exclude:
    - 'lib/ruby-next/core/**/*.rb'
